export const UNITS_DATA = {
  "lectura-critica": [
    {
      id: "unit-1",
      name: "Comprensión Literal",
      level: "Nivel 1",
      requiredScore: 7,
      description: "Identificar información explícita",
      questions: [
        {
          id: "q1",
          text: '¿Cuál es la idea principal del siguiente texto? "La educación es la base del desarrollo social..."',
          options: ["Desarrollo social", "Educación fundamental", "Base educativa", "Progreso nacional"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q2",
          text: "Según el texto, ¿qué factor es más importante para el aprendizaje?",
          options: ["Motivación", "Recursos", "Tiempo", "Ambiente"],
          correctAnswer: 0,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q3",
          text: "¿Cuál de las siguientes afirmaciones es correcta según el texto?",
          options: [
            "La lectura es opcional",
            "La lectura desarrolla el pensamiento",
            "La lectura es difícil",
            "La lectura es aburrida",
          ],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q4",
          text: "El autor menciona que la educación crítica permite:",
          options: ["Memorizar mejor", "Pensar de forma independiente", "Aprobar exámenes", "Leer más rápido"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q5",
          text: "¿Qué característica define al lector crítico?",
          options: ["Lee mucho", "Cuestiona lo que lee", "Lee rápido", "Recuerda todo"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q6",
          text: "El texto sostiene que la comprensión lectora es:",
          options: ["Innata", "Desarrollable", "Genética", "Permanente"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q7",
          text: "Según el fragmento, ¿cuál es el propósito de la lectura crítica?",
          options: ["Entretener", "Evaluar información", "Memorizar", "Competir"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q8",
          text: "¿Qué habilidad NO se menciona como parte de la lectura crítica?",
          options: ["Análisis", "Síntesis", "Velocidad", "Evaluación"],
          correctAnswer: 2,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q9",
          text: "El autor compara la lectura con:",
          options: ["Un viaje", "Una herramienta", "Un deporte", "Un juego"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
        {
          id: "q10",
          text: "¿Cuál es la conclusión principal del texto?",
          options: ["Leer es difícil", "La lectura crítica es esencial", "Los libros son caros", "La educación falla"],
          correctAnswer: 1,
          topic: "Comprensión literal",
          imageUrl : "https://d35aaqx5ub95lt.cloudfront.net/images/leagues/838ba65643baef4c8442317df514cab5.svg",
        },
      ],
    },
    {
      id: "unit-2",
      name: "Comprensión Inferencial",
      level: "Nivel 2",
      requiredScore: 7,
      description: "Deducir información implícita",
      questions: [],
    },
    {
      id: "unit-3",
      name: "Comprensión Crítica",
      level: "Nivel 3",
      requiredScore: 8,
      description: "Evaluar y valorar textos",
      questions: [],
    },
    {
      id: "unit-4",
      name: "Análisis Textual",
      level: "Nivel 4",
      requiredScore: 8,
      description: "Analizar estructura y propósito",
      questions: [],
    },
  ],
  matematicas: [
    {
      id: "unit-1",
      name: "Álgebra Básica",
      level: "Nivel 1",
      requiredScore: 7,
      description: "Operaciones algebraicas",
      questions: [],
    },
    {
      id: "unit-2",
      name: "Geometría",
      level: "Nivel 2",
      requiredScore: 7,
      description: "Figuras y áreas",
      questions: [],
    },
  ],
}
